apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nerium
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nerium
    spec:
      containers:
      - name: nerium
        image: us.gcr.io/lexical-cider-93918/nerium:latest
        ports:
        - containerPort: 8081
        volumeMounts:
        - name: dotenv
          mountPath: /dotenv
        - mountPath: /etc/ssl/certs
          name: ca-certificates
        securityContext:
          capabilities:
            add:
            - SYS_ADMIN
          privileged: true
        lifecycle:
          postStart:
            exec:
              command: ["gcsfuse", "nerium-sql", "/app/sqls"]
          preStop:
            exec:
              command: ["fusermount", "-u", "/app/sqls"]
      volumes:
      - name: dotenv
        secret:
          secretName: nerium-dotenv
          defaultMode: 0400
          items:
          - key: .env
            mode: 0400
            path: .env
      - name: ca-certificates
        hostPath:
          path: /etc/ssl/certs
