# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.5
        environment:
          PIPENV_VENV_IN_PROJECT: true

    working_directory: ~/nerium

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v2-deps-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          name: install dependencies
          command: |
            sudo pip3 install pipenv
            pipenv install -d
      - save_cache:
          paths:
            - ./. venv
          key: v2-deps-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          name: run tests
          command: |
            pipenv run coverage run tests.py
      - run:
          name: Send to Codecov
          command: bash <(curl -s https://codecov.com/bash)
      - store_artifacts:
          path: .coverage
          