# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.5
        environment:
          PIPENV_VENV_IN_PROJECT: true

    working_directory: ~/nerium

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-deps-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          name: install dependencies
          command: |
            sudo pip3 install pipenv
            pipenv install
      - save_cache:
          paths:
            - ./venv
            - "/usr/local/bin"
            - "/usr/local/lib/python3.6/site-packages"
          key: v1-deps-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          name: run tests
          command: |
            pipenv run coverage run tests.py

      - store_artifacts:
          path: test-reports
          destination: test-reports
          